//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everstox.API.IntegrationTests.Static_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Carriers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Carriers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Everstox.API.IntegrationTests.Static_Data.Carriers", typeof(Carriers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8d5998f4-f5ba-44a9-9062-fc77fd67f2e1.
        /// </summary>
        internal static string DHL_Id {
            get {
                return ResourceManager.GetString("DHL_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 453ac8ae-42f6-4356-90b8-e218d69c81d1.
        /// </summary>
        internal static string DPD_Id {
            get {
                return ResourceManager.GetString("DPD_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18c9ac6b-4de5-4959-b581-0216da1db5ee.
        /// </summary>
        internal static string HP_Id {
            get {
                return ResourceManager.GetString("HP_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f8c4c3be-5975-4945-a020-56a9cf177871.
        /// </summary>
        internal static string UPS_Id {
            get {
                return ResourceManager.GetString("UPS_Id", resourceCulture);
            }
        }
    }
}
