//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everstox.API.IntegrationTests.Static_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShipmentOptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipmentOptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Everstox.API.IntegrationTests.Static_Data.ShipmentOptions", typeof(ShipmentOptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9454c6fd-cef4-4498-b122-18ecd0776e87.
        /// </summary>
        internal static string DHLExpress_Id {
            get {
                return ResourceManager.GetString("DHLExpress_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9454c6fd-cef4-4498-b122-18ecd0776e88.
        /// </summary>
        internal static string DHLStandard_Id {
            get {
                return ResourceManager.GetString("DHLStandard_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9454c6fd-cef4-4498-b122-18ecd0776e98.
        /// </summary>
        internal static string FreeShipping_Id {
            get {
                return ResourceManager.GetString("FreeShipping_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f6ce66d9-fe9f-4444-a941-a9fd9e6dcd78.
        /// </summary>
        internal static string Standard_Id {
            get {
                return ResourceManager.GetString("Standard_Id", resourceCulture);
            }
        }
    }
}
