//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everstox.API.IntegrationTests.Static_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarehousesData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarehousesData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Everstox.API.IntegrationTests.Static_Data.WarehousesData", typeof(WarehousesData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77a87c74-489d-4de3-b362-3f9715f048ee.
        /// </summary>
        internal static string BolecWarehouse_Connector {
            get {
                return ResourceManager.GetString("BolecWarehouse_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 707cf259-51ef-4360-8647-6d9a106e8ce7.
        /// </summary>
        internal static string BolecWarehouse_Id {
            get {
                return ResourceManager.GetString("BolecWarehouse_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 867b086a-a79d-4521-84c6-a49559426a9b.
        /// </summary>
        internal static string DemoWarehouseQA1_Connector {
            get {
                return ResourceManager.GetString("DemoWarehouseQA1_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c52334fe-c579-48b3-8f9b-7230a2abf717.
        /// </summary>
        internal static string DemoWarehouseQA1_Id {
            get {
                return ResourceManager.GetString("DemoWarehouseQA1_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5070cae5-e1fd-4647-9941-bf9710cb0625.
        /// </summary>
        internal static string FinecomQA1_Connector {
            get {
                return ResourceManager.GetString("FinecomQA1_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 091eb34d-c2c8-4520-b6ea-cc2ab90cb0e5.
        /// </summary>
        internal static string FinecomQA1_Id {
            get {
                return ResourceManager.GetString("FinecomQA1_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e73ff472-c0ef-4010-9ae6-c0a55ef728c2.
        /// </summary>
        internal static string German_WH_Connector {
            get {
                return ResourceManager.GetString("German_WH_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2b595047-400f-4a7f-b303-2475c9855d81.
        /// </summary>
        internal static string German_WH_Id {
            get {
                return ResourceManager.GetString("German_WH_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c7e03b5f-c210-4967-b3cc-d3e95d1e5f91.
        /// </summary>
        internal static string IvanWarehouse_Connector {
            get {
                return ResourceManager.GetString("IvanWarehouse_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 526b129c-9db1-4203-80a5-1f1f7ca23bf1.
        /// </summary>
        internal static string IvanWarehouse_Id {
            get {
                return ResourceManager.GetString("IvanWarehouse_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 74d36162-a4f6-4a9b-9f11-345c83333c32.
        /// </summary>
        internal static string StorelogixQA1_Connector {
            get {
                return ResourceManager.GetString("StorelogixQA1_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 168fd242-fe2e-450f-b436-6cacbd84a176.
        /// </summary>
        internal static string StorelogixQA1_Id {
            get {
                return ResourceManager.GetString("StorelogixQA1_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47948d44-78e8-4101-9f81-dfa167055f85.
        /// </summary>
        internal static string USA_WH1_Connector {
            get {
                return ResourceManager.GetString("USA_WH1_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9dcf3cc1-fb2e-412f-ad91-1d651252d715.
        /// </summary>
        internal static string USA_WH1_Id {
            get {
                return ResourceManager.GetString("USA_WH1_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3c379bce-378c-45ae-920e-6f99099ac184.
        /// </summary>
        internal static string USA_WH2_Connector {
            get {
                return ResourceManager.GetString("USA_WH2_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a5c554ac-1fd2-4061-8f50-8268a6437921.
        /// </summary>
        internal static string USA_WH2_Id {
            get {
                return ResourceManager.GetString("USA_WH2_Id", resourceCulture);
            }
        }
    }
}
